RedHatInsights/turnpike

services/nginx/api_gateway.conf, services/web/app.py
With Fakamai integration, we receive a header: `x-rh-insights-forwarded-host`
which contains the actual hostname we need to set for our SP config, to match
the response from the IdP. In the case of CI for instance, this would be:
ci.internal.cloud.redhat.com
We need to ensure we set this for the `$proxy_host` value in order for our SP
to behave correctly, and for our redirect on `401` to use the correct hostname.
Locally, when this header is _not_ set, we should default this to use the actual
host.
=> Ensure we use the forwarded host header when it exists

dev-backends.yml, docker-compose.yml, services/nginx/Dockerfile, services/nginx/api_backends.conf, services/nginx/api_conf.d/ping_api.conf, services/nginx/api_gateway.conf, services/nginx/backend_template.conf.j2, services/nginx/build-backends.py, services/nginx/nginx.conf, services/nginx/turnpike-entrypoint.sh, services/web/Dockerfile, services/web/app.py, services/web/requirements.txt
Using a config map mounted at `/etc/turnpike/backends.yml`, this change
* makes nginx generate a `location` stanza for each route, enabling auth as specified
* makes the Flask auth service consult the config map for what authorization rules to apply
* supports using docker-compose to simulate the config map
=> Configure routes from config map

services/nginx/backend_template.conf.j2, services/web/app.py
While we generate the identity header from the auth service, we don't actually pass it along to the origin services. This fixes that. It also lets the ping service do some identity header debugging.
=> Pass identity header to services.

.env.example, docker-compose.yml
- reference the `SERVER_NAME` from the docs in `.env.example`
- swap `NGINX_PORT` with `NGINX_LISTEN` based on https://github.com/RedHatInsights/turnpike/commit/d0ab57e070c321f4a42fbcd54e3ea88da9978e87
=> Update docker-compose.yml to

dev-backends.yml, docs/index.md, docs/userflow.puml, services/web/app.py
Ahead of having some chroming in front of Turnpike, this sets up a way for the
front-end to grab identifying information from the SSO SAML assertion.
This will return the `x-rh-identity` header as JSON if it exists, otherwise returning
a JSON payload with an `error` message if it doesn't exist, or fails to parse.
- remove `/api/ping-service/ping` mocked service
- add `/api/turnpike/identity` utility endpoint
- updates docs to reflect this endpoint for consistency
- updates the backend config for this endpoint (will need to update config in app-interface)
=> Make `/api/ping-service/ping` a more useful `/api/turnpike/identity` endpoint

turnpike/__init__.py
This change ensures that if/when this file does not exist outside of a development
environment, the app will continue to boot.
Without this set, once deployed, Flask will fail to boot because the environment
variable `TURNPIKE_CONFIG` doesn't exist to point to a valid config file.
Reference: https://github.com/pallets/flask/blob/024f0d384cf5bb65c76ac59f8ddce464b2dc2ca1/src/flask/config.py#L89-L90
=> Ensure `silent` defaults to `True` in `app.config.from_envvar`

README.md, dev-backends.yml, docker-compose.yml, docs/architecture.puml, docs/index.md, docs/mtls.puml, scripts/setup_devel_env, turnpike/config.py, turnpike/plugins/x509.py
Note: I added a script: `scripts/setup_devel_env` which generate certs and configuration if they don't exist. It may prove useful in trying to test this change. This script configures against samltest.id, and generates a unique SP entityId, so that turnpike developers don't overwrite each other's configs accidentally.
The approach I took was to go ahead and have nginx perform the authentication (verifying the client cert against a CA), and then pass the client cert subject and issuer to the turnpike service for authorization logic.
Also, note that I changed the auth order to try x509 first. The service falls back to SAML if the x509 header is not present. In this way, an endpoint can support either authentication method (SAML for humans, mTLS for services).
`x509` auth takes a Python …
=> Add mTLS (x509) authentication method

turnpike/plugins/saml.py
Currently, the `auth_data` returned from `session["samlUserdata"].items()` is
a list of tuples, which means an authorization predicate to check against roles
in the SAML assertion would need to convert the object to a dictionary in order
to check for roles, something like:
```
auth:
saml: "'Employee' in dict(user)['Role']"
```
This change, using `session["samlUserdata"]` directly in the eval globals would
make it so we can do something like:
```
auth:
saml: "'Employee' in user['Role']"
```
=> Use the auth data dictionary for the predicate eval

README.md, turnpike/config.py, turnpike/plugins/saml.py
Adds an endpoint to the SAML plugin which, if `TESTING` is enabled, lets them mock what their SAML assertion should contain. If `TESTING` is not enabled, this endpoint 404's.
=> Add testing endpoint for mocking SAML.

docs/_index.md, templates/nginx.yml, templates/redis.yml, templates/web.yml, turnpike/config.py, turnpike/plugins/x509.py
The x.509 handling needs a PSK to be able to trust the headers when not forwarded by nginx itself.
Additionally, we need to rejigger the templates so that the ConfigMaps are parameterized, so they can be /lgtm'ed.
This does both.
=> Add PSK to x.509 handling and clean up templates

Pipfile, Pipfile.lock, turnpike/__init__.py, turnpike/metrics.py, turnpike/views.py
This adds the initial integration of Prometheus, by setting up a class which we
can grab the metric objects off of to increment/add to. Initially, this will
give us the out-of-the-box metrics of the library, but also `requests_total`, which
will look like:
```
requests_total{policy_status_code="401",service="rbac"} 1.0
requests_total{policy_status_code="200",service="rbac"} 1.0
```
To view the metrics locally, you can hit your web service directly, at the metrics
path: `/metrics`
Follow-ups:
- export metrics based on auth type
- export metrics for service request time taken
- enable metric scraping inside stage/prod clusters against the web service
=> Initial Prometheus integration

docker-compose.yml, nginx/nginx.conf, nginx/status.conf, templates/nginx.yml, templates/prometheus-nginx.yml
This adds a new server for 8888, which the exporter will use to mount the /metrics
endpoint on port 9113: http://prometheus-nginx:9113/metrics
To test this locally:
- run the images with docker-compose
- verify the /stub_status endpoint: http://nginx:8888/stub_status
- view metrics counts: http://prometheus-nginx:9113/metrics
Required changes in app-interface:
- requires a change to add port 8888 to the nginx service
- locally this should work with the config in the docker-compose file to connect
to the nginx service, but in our template we'll need to update this to talk to
the local nginx service in the namespace (http://nginx.svc.cluster.local:8888/stub_status)
=> Setup initial prometheus integration for nginx

build_deploy.sh, docker-compose.yml, nginx/Dockerfile-prometheus, templates/prometheus-nginx.yml
This sets up a centos base image from Quay (based on the other base images we
use for NGINX in the project) and pulls in the exporter from GitHub, builds the
binary and runs it directly.
=> Move off dockerhub image

templates/prometheus-nginx.yml
- remove `command` from template since we run this in the Dockerfile
- add `quay-cloudservices-pull` secret
=> Fix prometheus-nginx template issues

docker-compose.yml, nginx/nginx.conf, nginx/status.conf, templates/nginx.yml
This is causing a regression. We'll leave the `prometheus-nginx` config in place
and idle replicas for now.
=> Temporarily remove prometheus-nginx port from nginx config

Dockerfile
quay.io/app-sre/centos:8 is no longer available. We have https://issues.redhat.com/browse/RHCLOUD-11345
logged to move to a RHEL-based UBI, but this thread: https://coreos.slack.com/archives/CCRND57FW/p1600357665112500
explains the challenges.
As an interim solution to unblock deployments, we'll be moving to the official
Centos mirror on Quay.
The `PowerTools` > `powertools` change is explained here:
- https://wiki.centos.org/Manuals/ReleaseNotes/CentOS8.2011#Yum_repo_file_and_repoid_changes
- https://bugs.centos.org/view.php?id=17920
=> Update the Turnpike base image

Dockerfile, nginx/Dockerfile
Updating "**turnpike-nginx**" & "**turnpike-web**" Dockerfiles to use "_centos:stream8_" instead of "_centos:8_" as security updates and backporting are better supported. Moreover, the primary reason for this change is to mitigate CVE-2021-33910 in a timely manner. 
**RPM Update (CESA-2021:2717):**
- Important CentOS systemd Update (CVE-2021-33910)
- 239-31.el8_2.2   -->   239-48.el8
=> Updating "turnpike-nginx" & "turnpike-web" Dockerfiles to use centos/centos:stream8

nginx/Dockerfile-prometheus
The latest version, 0.9.0 requires Golang 1.16 [1]. The latest Golang in the Red
Hat registry is currently 1.15.13-3, meaning we need to pin at the last working
version for our builds to succeed.
**Testing:**
Confirm the following build works:
```
docker build --build-arg scrapeuri=http://nginx:8888/stub_status -f ./nginx/Dockerfile-prometheus .
```
[1] https://github.com/nginxinc/nginx-prometheus-exporter/issues/193
=> Pin the version of nginx-prometheus-exporter

README.md, turnpike/__init__.py, turnpike/views.py
In lieu of any current UI support, this will make it easier for teams to retrieve
their `session` cookie value for making any non-browser requests to their APIs.
The endpoint `https://internal.cloud.redhat.com/api/turnpike/session/` will now return a
payload structured as:
```
{
"session": "<SESSION_COOKIE_STRING>"
}
```
=> Add internal /api/turnpike/session/ endpoint

scripts/setup_devel_env
On a fresh clone of turnpike, `saml` folder does not exist.
This creates the folder in that case.
=> Adds checks for saml and create it if does not exist

build_deploy.sh
- `Podman` is now being used within the script as opposed to `Docker`.
- This is due to the migration of the Jenkins build job to a RHEL8 node.
- The Jenkins build job has migrated to a RHEL8 node to support the UBI8 build of Turnpike-Web.
=> Updating the build_deploy.sh to use Podman

templates/nginx.yml, templates/redis.yml, templates/web.yml
---
Updating the `Web`, `Nginx`, and `Redis` Templates to support the "REPLICAS" parameter. This change is to support the spin-down of the Turnpike FedRAMP Production environment.
=> Updating the Turnpike Templates to support the "REPLICAS" parameter

.dockerignore, Dockerfile-pr-check, pr_check.sh, pr_tests/pr_tests.sh
-----
- `nginx/build_config.py` was added as an exception within the `.dockerignore` file as it is needed to carry out the pytests.
- `Dockerfile-pr-check` was create to map out the containerized version of turnpike's pr checks.
- `pr_tests.sh` was create to instruct the PR CHECK container on how to carry out the pytests.
- `pr_check.sh` was rebuilt from the ground up to handle the Jenkins creation, running, teardown, and clean up of the containerized PR CHECK.
- ✅   `CentOS-Based` PR CHECK image was successfully built and ran locally _(Within RHEL8 environment)_
=> Pushing the new containerized PR_CHECK

Dockerfile
-----
The `Dockerfile` for `Turnpike-Web` has been updated to support the installation of Python38 and removed Python36 dependencies.
RPMs changes via `dnf` Command:
- `python3-pip` -> `python38-pip`
- Removed `python3-devel`
- ✅   `RHEL8-Based` image successfully built locally (within a RHEL8 VM)
=> Updating Dockerfile to support Python38

templates/prometheus-nginx.yml
Resolves an issue where app-interface MR checks don't handle null values. Their fix is here: https://github.com/app-sre/qontract-reconcile/pull/2626
=> Remove null volume template reference

Dockerfile, Dockerfile-env, Dockerfile-pr-check
This option is now deprecated, and is replaced by using `pipenv requirements`:
https://github.com/pypa/pipenv/releases/tag/v2022.8.13
=> Fix `pipenv lock --requirements`

.env.example, .pre-commit-config.yaml, dev-backends.yml, nginx/backend_template.conf.j2, nginx/build_config.py, pr_check.sh
Follow-up to the work in https://github.com/RedHatInsights/turnpike/pull/81
--
Jira: https://issues.redhat.com/browse/RHCLOUD-11173
When the NGINX server starts, and one or more upstream hosts can't be resolved,
NGINX fails to come online at all. This means pods will enter a crash loop, and
Turnpike will be down in the given environment.
To fix the issue, we need to ensure NGINX doesn't try to resolve all hosts at start,
and setting the proxy_pass value to a variable will lazily resolve the host.
The following changes work locally, and have been deployed and tested in stage.
- Configure a local regression API which will cause NGINX to fail to start if it
doesn't resolve without this fix in place.
- Update the location matcher so that we can explicitly proxy the entire request
path, which …
=> Use dynamic resolver from /etc/resolv.conf

.pre-commit-config.yaml, Dockerfile-pr-check, pr_check.sh, pr_tests/pr_tests.sh, requirements.txt
- https://issues.redhat.com/browse/RHCLOUD-21373
The security scanner, Snyk, requires the `requirements.txt` for Python-based vulnerability scanning. At this time, this repo uses Pipenv, which only generates a "Pipfile" and a Pipfile.lock".
This MR add `requirements.txt` to the repo. Additionally, the `.pre-commit-config.yaml` file has been update to use the following:
- **[pipenv-pre-commit](https://github.com/casey-williams-rh/pipenv-pre-commit)**
- Anytime a `Pipfile.lock` is committed this hook will generate an updated requirements.txt file.
`pr_check.sh` has been updated to specify the use of `Python 3.8` as opposed to the default `Python 3.6`. This change is due to `Python 3.6` not properly executing `pipenv`.
`pr_tests/pr_tests.sh` has been updated to clear the `pipenv` cache. The …
=> Updating pre-commit-config and adding requirements.txt

templates/nginx.yml, templates/web.yml
this PR adds exception for turnpike and DVO minimal three replicas check
- [RHCLOUD-19507](https://issues.redhat.com/browse/RHCLOUD-19507) [FIRING:2] deployment_validation_operator_minimum_three_replicas turnpike crcs02ue1 deployment-validation-operator-metrics deployment-validation-operator
- [RHCLOUD-19587](https://issues.redhat.com/browse/RHCLOUD-19587) [FIRING:2] deployment_validation_operator_minimum_three_replicas turnpike crcp01ue1 deployment-validation-operator-metrics deployment-validation-operator
=> exception for turnpike for DVO min 3 replicas

build_deploy.sh, nginx/Dockerfile-prometheus, nginx/api_gateway.conf.j2, templates/prometheus-nginx.yml
* updated the way nginx prometheus is built & deployed so we can set the scrape uri on deployment per env
* update the nginx prometheus dockerfile to use an environment variable to set `scrape_uri`, which points the nginx metrics exporter to the instance of nginx running
* add a parameter to the deployment template so we can set this variable per env
* remove build arg in build_deploy to not overwrite the env variable
~~## DO NOT MERGE
Must set the new required param `NGINX_SCRAPE_URI` in app interface first. I will update this when done
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/84811~~
edit: done
=> deploy nginx prometheus

nginx/Dockerfile-prometheus
update cmd in nginx dockerfile to run with shell so we can use env var
To test:
```
podman build -f ./nginx/Dockerfile-prometheus .
podman run -e SCRAPE_URI=http://localhost:8080/stub_status <image tag>
NGINX Prometheus Exporter version=0.11.0 commit=e4a6810d4f0b776f7fde37fea1d84e4c7284b72a date=2022-09-07T21:09:51Z, dirty=false, arch=linux/amd64, go=go1.19.13
2023/11/01 19:51:26 Starting...
2023/11/01 19:51:26 Could not create Nginx Client: failed to get http://localhost:8080/stub_status: Get "http://localhost:8080/stub_status": dial tcp [::1]:8080: connect: connection refused
```
that confirms the env var is read (im not actually running nginx locally so thats why connection refused but thats fine for this testing), vs right now if you build and run master the same way you will see …
=> update nginx prometheus dockerfile cmd

nginx/Dockerfile
**turnpike-nginx image:**
- enabled nginx:1.22 module
- use python3.11 module and fix vulnerabilities found by Grype tool
```
NAME        INSTALLED  FIXED-IN  TYPE    VULNERABILITY        SEVERITY 
pip         20.2.4     21.1      python  GHSA-5xp3-jfq3-5q8x  Medium    
setuptools  50.3.2     65.5.1    python  GHSA-r9hx-vwmv-q579  High   
```
=> nginx and nginx-prometheus images upgrade

Pipfile, Pipfile.lock, requirements.txt
upgrade of `async-timeout` package and its dependencies (this will solve failing tests in https://github.com/RedHatInsights/turnpike/pull/113 => tests are failing because the dependabot made changes only in `requirements.txt` but we need the same in the pipfiles)
=> upgraded package async-timetout

nginx/Dockerfile-prometheus
JIRA: [RHCLOUD-32214](https://issues.redhat.com/browse/RHCLOUD-32214)
use `git-core` instead of `git` package -> we need this only for clone the nginx-prometheus-exporter
=> [RHCLOUD-32214] use git-core in Dockerfile for turnpike-prometheus-nginx

Dockerfile, Dockerfile-pr-check
JIRA [RHCLOUD-32389](https://issues.redhat.com/browse/RHCLOUD-32389)
this is result from `python39` nad `python39-pip` install and both packages are installing same dependencies so I believe we can simplify our Dockerfile for `turnpike-web` image
```
dnf install -y python39
(1/6): python39-3.9.18-1.module+el8.9.0+20024+793d7211.aarch64.rpm
(2/6): python39-pip-wheel-20.2.4-8.module+el8.9.0+21344+82807453.1.noarch.rpm
(3/6): python39-pip-20.2.4-8.module+el8.9.0+21344+82807453.1.noarch.rpm
(4/6): python39-setuptools-wheel-50.3.2-4.module+el8.9.0+19644+d68f775d.noarch.rpm
(5/6): python39-setuptools-50.3.2-4.module+el8.9.0+19644+d68f775d.noarch.rpm
(6/6): python39-libs-3.9.18-1.module+el8.9.0+20024+793d7211.aarch64.rpm
dnf install -y python39-pip
(1/6): …
```
=> [RHCLOUD-32389] Dockerfile for turnpike-web image update - remove the redundant package

Dockerfile-env, pip.conf
JIRA [RHCLOUD-32389](https://issues.redhat.com/browse/RHCLOUD-32389)
the `Dockerfile-env` is used for local build for `turnpike-web` but right know its failing with
```
Collecting async-timeout==4.0.2
Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
ERROR: Could not find a version that satisfies the requirement blinker==1.7.0 (from versions: 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5)
ERROR: No matching distribution found for blinker==1.7.0
Error: building at STEP "RUN dnf install -y dnf-plugins-core &&     dnf config-manager --set-enabled powertools &&     dnf install -y gcc xmlsec1 xmlsec1-devel python3-pip python39 python3-devel libtool-ltdl-devel xmlsec1-openssl xmlsec1-openssl-devel openssl python39-devel &&     pip3 install --no-cache-dir --upgrade pip pipenv &&     pipenv …
```
=> [RHCLOUD-32389] Dockerfile-env for local development update

Dockerfile, nginx/Dockerfile, nginx/Dockerfile-prometheus
[RHCLOUD-32597](https://issues.redhat.com/browse/RHCLOUD-32597)
in all other services we use the latest ubi8 minimal without tag specification
=> [RHCLOUD-32597] use latest ubi8 minimal in all Dockerfiles

Dockerfile
the removing the `python3-devel` package doesnt have an effect because this package is not present in the container
```
No match for argument: python3-devel
No packages marked for removal.
Dependencies resolved.
Nothing to do.
```
but we can remove the python39-devel package ... I believe this was an intention but with all the python upgrades we forgot to update this line too
=> remove python39-devel from the turnpike-web Dockerfile

Dockerfile, Dockerfile-env, Dockerfile-pr-check
as discussed here https://github.com/RedHatInsights/turnpike/pull/138#discussion_r1600152233 
and recommended here https://hub.docker.com/_/python (in section How to use the this image) 
it is worthy (because of performance) to copy only the requirements (pipfiles) first and then rest of the files
=> docker files update - add requirements copy to improve the performance

Dockerfile
right now we use the `pipenv` to create `requirements.txt` file and then we install dependencies from this file with `pip`
but
we already have `requirements.txt` file in the repo so we don't need to install `pipenv` and use it only for this file generation
=> [RHCLOUD-32986] Dockerfile for turnpike-web image update - use only pip to install dependencies

nginx/Dockerfile-prometheus
[RHCLOUD-33805](https://issues.redhat.com/browse/RHCLOUD-33805)
https://github.com/nginxinc/nginx-prometheus-exporter
=> [RHCLOUD-33805] bump nginx-prometheus-exporter to the latest version

nginx/Dockerfile-prometheus
I found the deprecation warning in logs for the prometheus-nginx pod (turnpike) in OpenShift 
https://console-openshift-console.apps.crcp01ue1.o9m8.p1.openshiftapps.com/k8s/ns/turnpike-prod/pods/prometheus-nginx-644cc685f4-whnz6/logs
`the flag format is deprecated and will be removed in a future release, please use the new format: --nginx.scrape-uri`
=> used new flag format for parametr in Dockerfile for turnpike-prometheus-nginx

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, pr_check.sh
[RHCLOUD-36900](https://issues.redhat.com/browse/RHCLOUD-36900) 
moved pre-commit check in own github action
and
update `black` to the latest version in pre-commit config
---
motivation: in previous version the pre-commit check runs via Jenkins worker with python 3.8 and that was not align with python 3.9 we use in the project, additionally it was not possible to use latest `black` version (requires python >= 3.9)
moving into own github action we can better distinguish between pre-commit checks and rest pr check defined in the `pr_check.sh`
=> [RHCLOUD-36900] add pre-commit github action into repo

.dockerignore, nginx/.dockerignore
[RHCLOUD-32031](https://issues.redhat.com/browse/RHCLOUD-32031)
one of recommendations in [Credential Leak Self Assessment](https://docs.google.com/document/d/1IsX7NmMnWPcuOseyjjUj_T9VjBXx7p3UjWs5eNpDHyI/edit?tab=t.0) document is to add `.dockerignore` file into repository
=> [RHCLOUD-32031]  update .dockerignore

build_deploy.sh
[RHCLOUD-32031](https://issues.redhat.com/browse/RHCLOUD-32031)
according step 1 in [Credential Leak Self Assessment document ](https://docs.google.com/document/d/1IsX7NmMnWPcuOseyjjUj_T9VjBXx7p3UjWs5eNpDHyI/edit?tab=t.0) use temp directory for podman config
=> [RHCLOUD-32031] use temp directory for podman config

Dockerfile, Dockerfile-env, Dockerfile-pr-check, nginx/Dockerfile, nginx/Dockerfile-prometheus
[RHCLOUD-37573](https://issues.redhat.com/browse/RHCLOUD-37573)
base image ubi8/ubi-minimal in the RH catalog: https://catalog.redhat.com/software/containers/ubi8-minimal/5c64772edd19c77a158ea216?container-tabs=overview
this change will enable the Konflux Bot to automatically detect when a new base image version is released and create a PR for the update and we will have better control over the base image version
=> [RHCLOUD-37573] specify the base image version in dockerfiles

nginx/Dockerfile
[RHCLOUD-38790](https://issues.redhat.com/browse/RHCLOUD-38790)
=> [RHCLOUD-38790] enable new version of nginx in Dockerfile

.tekton/turnpike-nginx-prometheus-pull-request.yaml, .tekton/turnpike-nginx-prometheus-push.yaml, .tekton/turnpike-nginx-pull-request.yaml, .tekton/turnpike-nginx-push.yaml, .tekton/turnpike-web-pull-request.yaml, .tekton/turnpike-web-push.yaml
https://issues.redhat.com/browse/KONFLUX-2264
Context:
Related slack thread: https://redhat-internal.slack.com/archives/C059NUD49PD/p1742912856679589
-  there are new checks required to be added to konflux pipelines in order to pass the enterprise contract
- these checks are required to be installed by April 1st.
=> Add shell and unicode sast pipeline tasks

Pipfile.lock
This reverts commit 823bd87586f52df5bf079058ca96ba745a4178da.
because turnpike-web pods crash loop back-off
=> Revert "Lock file maintenance"

Pipfile, Pipfile.lock
The "xmlsec" library is currently suffering from an issue[1] that makes the builds fail due to some version mismatch with the "libxml" library.
Applying some restrictions to the underlying "lxml" library should be enough to work around the issue for now, until the above issue is fixed.
[1]: https://github.com/xmlsec/python-xmlsec/issues/320
=> chore: restrict "lxml" version

.pre-commit-config.yaml, Pipfile, Pipfile.lock, mypy.ini
you can run the type annotation check via
```
$ mypy .
```
(in that case the configuration from `mypy.ini`  file is used
------
or as part of pre-commit check
```
$ pre-commit run -av
```
-------
the check will be now part of the [pre-commit](https://github.com/RedHatInsights/turnpike/actions/workflows/pre-commit.yml) github action too
=> add type annotation check in the ci

tests/test_oidc_plugin.py, turnpike/plugins/oidc/oidc.py
When a back end did not have an "oidc" section in the "auth" section, the plug in was returning "500" errors, when it should simply be skipping the authorization attempt for that back end.
The reason for this was that I mistakenly understood that if a plug in gets executed, that meant that the back end had an authorization section defined for that plug in.
However, in reality, Turnpike loops through the plug ins and skips the authorization when there is no section defined in the "auth" key for that plugin.
[[RHCLOUD-30610]](https://issues.redhat.com/browse/RHCLOUD-30610)
=> RHCLOUD-30610 | fix: the "oidc" plugin is not skipped

docs/_index.md
The page with the information on how to use the different authentication mechanisms has changed, so the links needed to be updated.
[[RHCLOUD-30610]](https://issues.redhat.com/browse/RHCLOUD-30610)
=> RHCLOUD-30610 | docs: update links to the required elements to make requests

nginx/configuration_builder/templates/nginx_location_template.conf.j2, templates/web.yml, tests/test_matcher.py, turnpike/config.py, turnpike/views.py
The reason why regex was being used for the location matching was because the captured group was being passed to the "proxy_pass" as the "$1" argument. So, for a backend like this one...
- Origin: http://my-service.svc.cluster.local
- Route: /api/my-service
... and a request sent to "/api/my-service/resource/subresource", the following URL was constructed in Nginx:
- http://my-service.svc.cluster.local/resource/subresource
I still believe it would be benefitial to move away from regex matchings since it would make our lives easier, but until we figure out a solution to appending the URI I'll revert the changes to unblock other teams.
[[RHCLOUD-33532]](https://issues.redhat.com/browse/RHCLOUD-33532)
=> RHCLOUD-33532 | fix: partially revert Nginx location matching

.env.example, dev-backends.yml, docker-compose.yml, templates/web.yml, turnpike/config.py, turnpike/plugins/vpn.py
Add the option to require users be on vpn for a backend/api
Akamai has exposed new domains that are restricted behind the vpn:
```
private.console.redhat.com
private.cloud.redhat.com
private.console.stage.redhat.com
private.cloud.stage.redhat.com
```
So to restrict a backend to be vpn only, we need to enforce that the request came from one of those domains. I did this via creating a new turnpike plugin that will check backend config to see if it is vpn only, and if yes, verify the request came from `private.*` by examining the `x-rh-edge-host` header that akami sets on incoming requests.
The turnpike backend config now has a new `private` option:
```
- name: vpn_restricted_api
route: /api/vpn-only/
private: true
origin: http://my-service.svc.cluster.local:8080/api/vpn-only/
auth: 
saml: …
```
=> allow backends to be restricted to vpn only

.github/labeler.yml, .github/workflows/labeler.yml
[RHCLOUD-41021](https://issues.redhat.com/browse/RHCLOUD-41021)
github action will add "bot" label automatically on every PR created by konflux bot or dependabot, we can set new rules in the future to add labels on our PRs if needed via config in `.github/labeler.yml`
=> [RHCLOUD-41021] add github action Labeler

docker-compose.yml, nginx/configuration_builder/build_config.py, nginx/configuration_builder/templates/api_gateway.conf.j2, nginx/configuration_builder/templates/nginx_location_template.conf.j2, templates/nginx.yml
The Flask server name's removal is causing issues when fetching the
session from Turnpike, because when the configuration is loaded from the
Flask application when Nginx is booting, the "X-Forwarded-Host" header
contains the improper hostname.
=> RHCLOUD-37506 | revert: fix flask server name removal

tests/test_header_validator.py, tests/test_vpn_plugin.py, turnpike/plugins/common/header_validator.py, turnpike/plugins/common/invalid_header_error.py, turnpike/plugins/common/non_vpn_edge_host_header_error.py, turnpike/plugins/vpn.py
I did not know that Akamai sets the "X-Rh-Edge-Host" header for MTLS authentications too, and due to that mistake some of the requests are being rejected.
This fix should still add the Nginx header flag for all the requests that come from the VPN, and let the rest of the requests through.
=>  RHCLOUD-37506 | fix: MTLS requests denied for non-private backends

.gitignore, nginx/configuration_builder/templates/api_gateway.conf.j2, nginx/configuration_builder/templates/nginx_location_template.conf.j2, templates/nginx.yml, templates/web.yml, tests/test_matcher.py, tests/test_vpn_plugin.py, turnpike/__init__.py, turnpike/config.py, turnpike/plugin.py, turnpike/plugins/auth.py, turnpike/plugins/saml.py, turnpike/plugins/vpn.py, turnpike/views/saml/acs_view.py, turnpike/views/saml/generic_saml_view.py, turnpike/views/saml/login_view.py, turnpike/views/saml/metadata_view.py, turnpike/views/saml/mock_assertion_view.py, turnpike/views/saml/saml_context.py, turnpike/views/saml/saml_settings_type.py, turnpike/views/saml/sls_view.py, turnpike/views/views.py
In order to be able to provide SAML authentication for both the "internal" and "private" networks, the Flask application required two SAML clients set up.
We attempted using Flask's session to build the proper request context depending on whether the user was sending the request from the "internal" or the "private" network. However, as soon as the user attempted logging in by hitting the SAML endpoint from the "private" network, we set the session flag in Flask's session and the subsequent requests —regardless of which network the request came from— would be redirected to the "private" network, because the "OneLogin" utility would generate that redirect from the "private" settings.
These changes split the SAML views and the plug in in different files to make it easier to reason about how …
=> RHCLOUD-37506 | RHCLOUD-41155 | feature: make Turnpike handle "internal" and "private" SAML auths

turnpike/config.py, turnpike/plugins/saml.py, turnpike/views/saml/acs_view.py, turnpike/views/saml/login_view.py, turnpike/views/saml/metadata_view.py, turnpike/views/saml/saml_context.py, turnpike/views/saml/sls_view.py
The imports are causing the pods to crashloop because I incorrectly added the wrong import for the "Optional" class.
=> RHCLOUD-37506 | fix: imports

nginx/configuration_builder/templates/api_gateway.conf.j2, nginx/nginx.conf
We were interested in the value of the "X-Edge-Host" header, which is
the one that we use in the VPN plug in too to determine to which host we
need to redirect the user.
=> RHCLOUD-37506 | fix: redirections to the private network are not working

templates/web.yml, tests/test_matcher.py, turnpike/config.py, turnpike/views/views.py
The changes have been tested in stage and everything seems to work as intended, so we should be good to remove the safety flag.
[[RHCLOUD-33532]](https://issues.redhat.com/browse/RHCLOUD-33532)
=> RHCLOUD-33532 | feature: enable back end matching by name by default
