RedHatInsights/turnpike

- scripts/push
Here's an interim script to push the image to OpenShift manually for testing.
> Add script to push code to OpenShift

- docs/_index.md
- update docs to point to stage LDAP group management
- update reference to SAML `Role` object
> Add a note regarding stage LDAP groups

- docs/_index.md
I think this is the correct path we want?
> Fix doc reference to the Turnpike deploy file

- .pre-commit-config.yaml
- Dockerfile
- Dockerfile-env
- Dockerfile-pr-check
- Pipfile
- Pipfile.lock
- nginx/Dockerfile
3.6 is EOL and is causing issues with pipenv.
> Upgrade to Python 3.8

- templates/prometheus-nginx.yml
validate locally with 
```
oc process -f templates/prometheus-nginx.yml --local -p IMAGE_TAG=e64a61d -p NGINX_SCRAPE_URI=foobar
```
> nginx prometheus deploy template fix

- turnpike/plugins/rh_identity.py
Seems to have broken with recent dep updates
> Fix x-rh-identity header encoding

- dashboards/grafana-dashboard-turnpike.configmap.yaml
added new fields for requests counts by status and CPU/memory usage metrics
> updated Grafana Dashboard for Turnpike 

- turnpike/plugins/saml.py
These logging will be removed once we find the root cause
> Add some temp logging for debug

- README.md
JIRA: https://issues.redhat.com/browse/RHCLOUD-28954
> Update README to link to more detailed docs

- Dockerfile
- nginx/Dockerfile
- nginx/Dockerfile-prometheus
JIRA [RHCLOUD-32295](https://issues.redhat.com/browse/RHCLOUD-32295)
> [RHCLOUD-32295] base image upgrade to the latest version

- .pre-commit-config.yaml
[RHCLOUD-32621](https://issues.redhat.com/browse/RHCLOUD-32621)
- update pre-commit hook version
> [RHCLOUD-32621] Pre commit update

- Dockerfile
- Dockerfile-pr-check
it is not needed to copy only pipfiles and then all folder content
before
```
COPY ./Pipfile ./Pipfile.lock /usr/src/app/
COPY . /usr/src/app/
```
now
```
COPY . /usr/src/app/
```
> Dockerfile strukture update

- templates/web.yml
restartPolicy: Forbidden: may not be set for non-init containers
> Fix template issue

- nginx/Dockerfile-prometheus
[RHCLOUD-34979](https://issues.redhat.com/browse/RHCLOUD-34979)
> [RHCLOUD-34979] bump nginx-prometheus-exporter to the latest version

- .tekton/turnpike-nginx-pull-request.yaml
- .tekton/turnpike-nginx-push.yaml
Next step in konflux migration: update source image default variable to true so we can build source image
> Update source image default variable to true to buliding source image

- .pre-commit-config.yaml
- .tekton/turnpike-web-pull-request.yaml
- konflux-pr-check.sh
- pr_check.sh
Adding the unit tests to run in turnpike-web pull request
> [KONFLUX] Add Unit Tests to turnpike-web

- templates/nginx.yml
- templates/prometheus-nginx.yml
- templates/web.yml
Create image parameter and variable for web, nginx, and nginx-prometheus images
> [KONFLUX] Create image parameter for web, nginx, and nginx-prometheus images

- Pipfile
- Pipfile.lock
- requirements.txt
[RHCLOUD-36499](https://issues.redhat.com/browse/RHCLOUD-36499)
> [RHCLOUD-36499] upgrade async-timeout package to the latest version

- Pipfile
- Pipfile.lock
- requirements.txt
[RHCLOUD-36572](https://issues.redhat.com/browse/RHCLOUD-36572)
> [RHCLOUD-36572] upgrade prometheus-client to the latest version

- Pipfile
- Pipfile.lock
- requirements.txt
[RHCLOUD-36581](https://issues.redhat.com/browse/RHCLOUD-36581)
> [RHCLOUD-36581] update redis package to the latest version

- nginx/Dockerfile-prometheus
[RHCLOUD-37035](https://issues.redhat.com/browse/RHCLOUD-37035)
> [RHCLOUD-37035] update nging-prometheus-exporter to the latest version

- .github/workflows/json-yaml-validation.yml
[RHCLOUD-37198](https://issues.redhat.com/browse/RHCLOUD-37198)
> [RHCLOUD-37198] add json and yaml basic validator into ci

- nginx/Dockerfile-prometheus
[RHCLOUD-37251](https://issues.redhat.com/browse/RHCLOUD-37251)
> [RHCLOUD-37251] bump nginx-prometheus-exporter to the latest version

- Pipfile
- Pipfile.lock
- requirements.txt
[RHCLOUD-37308](https://issues.redhat.com/browse/RHCLOUD-37308)
> [RHCLOUD-37308] bump redis to the latest version

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- konflux-pr-check.sh
[RHCLOUD-37641](https://issues.redhat.com/browse/RHCLOUD-37641)
> [RHCLOUD-37641] bump black to the latest version

- .github/workflows/security-workflow-template.yml
[RHCLOUD-37748](https://issues.redhat.com/browse/RHCLOUD-37748)
- new names for security scans to better distinguish the components
- add security scan for turnpike-web image
> [RHCLOUD-37748] add security check GH workflow for turnpike-web image

- Dockerfile
- Dockerfile-pr-check
- nginx/Dockerfile
- nginx/Dockerfile-prometheus
https://issues.redhat.com/browse/RHCLOUD-35257
> RHCLOUD-35257 - ubi8 to ubi9 update

- README.md
Remigration of turnpike pipelines
Testing them to make sure that everything works
> Testing with the turnpike pipelines

- .tekton/turnpike-web-pull-request.yaml
- konflux-pr-check.sh
Adding the unit tests to the turnpike-web-pull-request pipeline
> Add the unit tests to turnpike-web-pull-request pipeline

- Pipfile
- Pipfile.lock
This reverts commit 0961a2958ac3ea71478c81ab9297e38fc73c8aa2.
> Revert "Update dependency redis to v5.3.0"

- Pipfile
- Pipfile.lock
- nginx/api_gateway.conf.j2
- nginx/backend_template.conf.j2
- tests/backends/test-backends.yaml
- tests/mocked_plugins/mocked_plugin.py
- tests/test_matcher.py
- turnpike/__init__.py
- turnpike/views.py
We had issues determining which back end was matched in Nginx and Turnpike in the past, which led to uncountable debugging time.
[[RHCLOUD-33532]](https://issues.redhat.com/browse/RHCLOUD-33532)
> RHCLOUD-33532 | feature: improve back end matching

- turnpike/plugins/saml.py
Reverts RedHatInsights/turnpike#418
> Revert "added log to saml plugin"

- Pipfile
- Pipfile.lock
This reverts commit c116d3e1167065a72bc9027c33ca3bbbedbd6cc5.
> Revert "chore(deps): update dependency xmlsec to v1.3.16"

- nginx/configuration_builder/templates/api_gateway.conf.j2
- turnpike/plugins/saml.py
The debug statements will help us figure out the redirects.
> RHCLOUD-37506 | debug: debug statements

- nginx/configuration_builder/templates/api_gateway.conf.j2
> RHCLOUD-37506 | debug: fix Nginx header

- .gitignore
> chore: Ignore IDEA files from the repository

- Dockerfile
- nginx/Dockerfile
Tempfix for High cve found in ubi image
> tempfix for sqllite-lib cve
